"""initial schema — all 33 tables, locations partitioning, functions, indexes

Revision ID: 0001_initial_schema
Revises:
Create Date: Sprint 0

This bootstrap migration applies the canonical DDL from ``backend/db/schema.sql``
(the human-readable source of truth). It is executed by Alembic's SYNC engine
(psycopg2 — see alembic/env.py), so the multi-statement DDL, the
``create_locations_partition`` PL/pgSQL function, and the ``DO`` bootstrap block
that creates monthly partitions all run in a single pass.

Subsequent schema changes use normal incremental autogenerated migrations; this
file remains the immutable "table zero" snapshot. schema.sql is kept in sync as
documentation.
"""
from __future__ import annotations

from pathlib import Path

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

# backend/alembic/versions/0001_initial_schema.py -> parents[2] == backend/
SCHEMA_SQL = Path(__file__).resolve().parents[2] / "db" / "schema.sql"


def upgrade() -> None:
    ddl = SCHEMA_SQL.read_text(encoding="utf-8")
    op.execute(ddl)


def downgrade() -> None:
    # Initial migration: a clean teardown resets the public schema entirely
    # (drops all 33 tables, partitions, functions, and the updated_at trigger),
    # then restores the pgcrypto extension the app relies on.
    op.execute(
        """
        DROP SCHEMA public CASCADE;
        CREATE SCHEMA public;
        CREATE EXTENSION IF NOT EXISTS pgcrypto;
        """
    )
